package gr.aueb.cf.schoolapp.model;

import gr.aueb.cf.schoolapp.core.enums.RoleType;
import jakarta.persistence.*;
import lombok.*;

import java.security.Principal;

/**
 * Represents an application user in the system.
 *
 * <p>This entity maps to the {@code users} table in the database.
 * Each user has a unique username, a password, and a role type.</p>
 *
 * <p>Implements {@link Principal} to allow integration with security frameworks
 * (e.g., Jakarta Security, JAX-RS security).</p>
 *
 * <p>Extends {@link AbstractEntity} for shared entity properties (e.g., audit fields)
 * and implements {@link IdentifiableEntity} to guarantee an identifier.</p>
 */
@Entity
@NoArgsConstructor
@AllArgsConstructor
@Getter
@Setter
@Builder
@Table(name = "users")
public class User extends AbstractEntity implements IdentifiableEntity, Principal {

    /** Primary key of the user, autogenerated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique username used for authentication. */
    @Column(unique = true)
    private String username;

    /** Hashed password of the user. */
    private String password;

    /** Role assigned to the user (e.g., ADMIN, TEACHER, STUDENT). */
    @Column(name = "role")
    @Enumerated(EnumType.STRING)
    private RoleType roleType;

    /**
     * Returns the username of the user.
     *
     * <p>Required by the {@link Principal} interface for security purposes.</p>
     *
     * @return the username of the user
     */
    @Override
    public String getName() {
        return username;
    }
}
